### PR TITLE
ESP32 support

### PR DESCRIPTION
**Pull request by h3ndrik**
introduce a few #ifdef to support ESP32.

- os_printf(...) is not available on esp32. we could use ESP_LOGx() macros but these are not available on other platforms, so do a Serial.printf() instead
- the WiFi library is called WiFi.h
- all the area_update_... commands are not available in the Adafruit library i found. so replace them.

### CODE REVIEW

**Comment by Links2004** [comment]
yay, looking good, thanks.
which frame rate did you get with a ESP32?

**Comment by h3ndrik** [comment]
i'm getting 8fps with slightly modified example code and tightvnc. i'll leave a comment if i find out how to speed things up.
also i'm afraid the endian-ness is wrong. i'll open another pull-request for this.

**Comment by Links2004** [comment]
the low FPS is most likely from the Adafruit_ILI9341 lib, the code there is basically non optimized
for the ESP8266 I have a full rewrite:
https://github.com/Links2004/Adafruit_ILI9341 with it I where getting 20-25 fps on the ESP8266 ;)

after a short look at the current code of Adafruit, it look like they still are not able to use the SPI interface of the ESP to there full there full advantage (3 years later).
the ESP32 hat the same FIFO capabilities then the ESP8266 so there is much to gain there.

**Comment by h3ndrik** [comment]
still getting around 9fps with the standard adafruit library.
maybe one could use https://github.com/Bodmer/TFT_eSPI which gives me better results anyways. but i don't have enough spare time at hand to do this. at least at the moment.

**Pull request merged**
